language: ruby
rvm:
  - 2.6.1

dist: xenial

before_install:
  - 'sudo apt-get update'
  - 'sudo apt-get install vim-gnome'
  - 'vim --version'

script: xvfb-run bundle exec rake

notifications:
  email: false
