language: ruby
rvm:
  - 2.6.1

dist: xenial

before_install: |
  sudo apt-get update
  sudo apt-get install vim-gnome
  vim --version

  cp vimrc ~/.vimrc
  mkdir -p ~/.vim/{pack,swp,spell,undo}
  cp -ar pack ~/.vim/pack
  cp -ra swp ~/.vim/swp
  cp -ra spell ~/.vim/spell
  cp -ra undo ~/.vim/undo

script: |
  xvfb-run bundle exec rake

notifications:
  email: false
