language: ruby
rvm:
  - 2.6.1

dist: bionic

before_install: |
  sudo apt-get update
  sudo apt-get install -y vim-gnome xvfb
  vim --version

  # ------------------------------------------------------------
  # Brew
  # ------------------------------------------------------------

  # From <https://docs.brew.sh/Homebrew-on-Linux>
  sudo apt-get install build-essential curl file git gcc

  git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew
  mkdir -p ~/.linuxbrew/bin
  ln -sf ../Homebrew/bin/brew ~/.linuxbrew/bin
  eval "$(~/.linuxbrew/bin/brew shellenv)"

  travis_wait brew install --build-from-source ./vim.rb

  rm -rf ~/.vim*
  git clone --verbose --recursive https://github.com/jethrodaniel/.vim ~/.vim

script: |
  xvfb-run bundle exec rake

notifications:
  email: false
