language: ruby
rvm:
  - 2.6.1

dist: xenial

before_install: |
  sudo apt-get update
  sudo apt-get install vim-gnome xvfb
  vim --version

  rm -rf ~/.vim*
  git clone --recurse-submodules https://github.com/jethrodaniel/.vim ~/.vim

script: |
  xvfb-run bundle exec rake

notifications:
  email: false
