# Travis CLI settings

language: bash

dist: bionic

services: xfvb

before_install:
  - 'sudo apt-get update'
  - 'sudo apt-get install xfvb vim-gnome'
  - 'vim --version'

script: xvfb-run bundle exec rspec
